/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLRosetaskApiMessagesTaskResponseMessage.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   rosetask/v1
// Description:
//   Rose Task API
// Classes:
//   GTLRosetaskApiMessagesTaskResponseMessage (0 custom class methods, 4 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLRosetaskApiMessagesTaskUserResponseMessage;

// ----------------------------------------------------------------------------
//
//   GTLRosetaskApiMessagesTaskResponseMessage
//

@interface GTLRosetaskApiMessagesTaskResponseMessage : GTLObject
@property (retain) GTLRosetaskApiMessagesTaskUserResponseMessage *assignedTo;
@property (retain) NSNumber *complete;  // boolValue

// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (retain) NSNumber *identifier;  // longLongValue

@property (copy) NSString *text;
@end
