/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLRosetaskApiMessagesTaskResponseMessage.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   rosetask/v1
// Description:
//   Rose Task API
// Classes:
//   GTLRosetaskApiMessagesTaskResponseMessage (0 custom class methods, 5 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLRosetaskApiMessagesTaskUserResponseMessage;

// ----------------------------------------------------------------------------
//
//   GTLRosetaskApiMessagesTaskResponseMessage
//

// ProtoRPC message definition to return a Task

@interface GTLRosetaskApiMessagesTaskResponseMessage : GTLObject

// ProtoRPC message definition to return a TaskUser
@property (retain) GTLRosetaskApiMessagesTaskUserResponseMessage *assignedTo;

@property (retain) NSNumber *complete;  // boolValue
@property (copy) NSString *details;

// identifierProperty property maps to 'identifier' in the JSON ('identifier' is
// reserved for remapping 'id').
@property (retain) NSNumber *identifierProperty;  // longLongValue

@property (copy) NSString *text;
@end
