/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLRosetaskApiMessagesTaskListResponseMessage.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   rosetask/v1
// Description:
//   Rose Task API
// Classes:
//   GTLRosetaskApiMessagesTaskListResponseMessage (0 custom class methods, 4 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLRosetaskApiMessagesTaskResponseMessage;
@class GTLRosetaskApiMessagesTaskUserResponseMessage;

// ----------------------------------------------------------------------------
//
//   GTLRosetaskApiMessagesTaskListResponseMessage
//

// ProtoRPC message definition to return a TaskList

@interface GTLRosetaskApiMessagesTaskListResponseMessage : GTLObject

// identifierProperty property maps to 'identifier' in the JSON ('identifier' is
// reserved for remapping 'id').
@property (retain) NSNumber *identifierProperty;  // longLongValue

// ProtoRPC message definition to return a TaskUser
@property (retain) NSArray *taskUsers;  // of GTLRosetaskApiMessagesTaskUserResponseMessage

// ProtoRPC message definition to return a Task
@property (retain) NSArray *tasks;  // of GTLRosetaskApiMessagesTaskResponseMessage

@property (copy) NSString *title;
@end
