/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLRosetaskTaskProtoIdTextTaskListIdDetailsCompleteAssignedToEmail.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   rosetask/v1
// Description:
//   Rose Task API
// Classes:
//   GTLRosetaskTaskProtoIdTextTaskListIdDetailsCompleteAssignedToEmail (0 custom class methods, 6 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLRosetaskTaskProtoIdTextTaskListIdDetailsCompleteAssignedToEmail
//

@interface GTLRosetaskTaskProtoIdTextTaskListIdDetailsCompleteAssignedToEmail : GTLObject
@property (copy) NSString *assignedToEmail;
@property (retain) NSNumber *complete;  // boolValue
@property (copy) NSString *details;

// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (retain) NSNumber *identifier;  // longLongValue

@property (retain) NSNumber *taskListId;  // longLongValue
@property (copy) NSString *text;
@end
