/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLRosetaskApiMessagesTaskListListResponse.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   rosetask/v1
// Description:
//   Rose Task API
// Classes:
//   GTLRosetaskApiMessagesTaskListListResponse (0 custom class methods, 1 custom properties)

#import "GTLRosetaskApiMessagesTaskListListResponse.h"

#import "GTLRosetaskApiMessagesTaskListResponseMessage.h"

// ----------------------------------------------------------------------------
//
//   GTLRosetaskApiMessagesTaskListListResponse
//

@implementation GTLRosetaskApiMessagesTaskListListResponse
@dynamic items;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLRosetaskApiMessagesTaskListResponseMessage class]
                                forKey:@"items"];
  return map;
}

@end
