/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLRosetaskApiMessagesTaskUserResponseMessage.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   rosetask/v1
// Description:
//   Rose Task API
// Classes:
//   GTLRosetaskApiMessagesTaskUserResponseMessage (0 custom class methods, 3 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLRosetaskApiMessagesTaskUserResponseMessage
//

@interface GTLRosetaskApiMessagesTaskUserResponseMessage : GTLObject
@property (copy) NSString *googlePlusId;
@property (copy) NSString *lowercaseEmail;
@property (copy) NSString *preferredName;
@end
