/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLRosetaskApiMessagesTaskListResponseMessage.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   rosetask/v1
// Description:
//   Rose Task API
// Classes:
//   GTLRosetaskApiMessagesTaskListResponseMessage (0 custom class methods, 4 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLRosetaskApiMessagesTaskResponseMessage;
@class GTLRosetaskApiMessagesTaskUserResponseMessage;

// ----------------------------------------------------------------------------
//
//   GTLRosetaskApiMessagesTaskListResponseMessage
//

@interface GTLRosetaskApiMessagesTaskListResponseMessage : GTLObject

// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (retain) NSNumber *identifier;  // longLongValue

@property (retain) NSArray *taskUsers;  // of GTLRosetaskApiMessagesTaskUserResponseMessage
@property (retain) NSArray *tasks;  // of GTLRosetaskApiMessagesTaskResponseMessage
@property (copy) NSString *title;
@end
