/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLRosetaskApiMessagesTaskListListResponse.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   rosetask/v1
// Description:
//   Rose Task API
// Classes:
//   GTLRosetaskApiMessagesTaskListListResponse (0 custom class methods, 1 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLRosetaskApiMessagesTaskListResponseMessage;

// ----------------------------------------------------------------------------
//
//   GTLRosetaskApiMessagesTaskListListResponse
//

// ProtoRPC message definition to represent a list of task lists.

// This class supports NSFastEnumeration over its "items" property. It also
// supports -itemAtIndex: to retrieve individual objects from "items".

@interface GTLRosetaskApiMessagesTaskListListResponse : GTLCollectionObject

// ProtoRPC message definition to return a TaskList
@property (retain) NSArray *items;  // of GTLRosetaskApiMessagesTaskListResponseMessage

@end
