/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLRosetaskTaskUser.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   rosetask/v1
// Description:
//   Rose Task API
// Classes:
//   GTLRosetaskTaskUser (0 custom class methods, 5 custom properties)

#import "GTLRosetaskTaskUser.h"

// ----------------------------------------------------------------------------
//
//   GTLRosetaskTaskUser
//

@implementation GTLRosetaskTaskUser
@dynamic created, googlePlusId, lowercaseEmail, preferredName, taskListKeys;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      @"google_plus_id", @"googlePlusId",
      @"lowercase_email", @"lowercaseEmail",
      @"preferred_name", @"preferredName",
      @"task_list_keys", @"taskListKeys",
      nil];
  return map;
}

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[NSString class]
                                forKey:@"task_list_keys"];
  return map;
}

@end
