/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLRosetaskTaskUser.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   rosetask/v1
// Description:
//   Rose Task API
// Classes:
//   GTLRosetaskTaskUser (0 custom class methods, 5 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLRosetaskTaskUser
//

@interface GTLRosetaskTaskUser : GTLObject
@property (copy) NSString *created;
@property (copy) NSString *googlePlusId;
@property (copy) NSString *lowercaseEmail;
@property (copy) NSString *preferredName;
@property (retain) NSArray *taskListKeys;  // of NSString
@end
