/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLRosetaskApiMessagesTaskUserResponseMessage.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   rosetask/v1
// Description:
//   Rose Task API
// Classes:
//   GTLRosetaskApiMessagesTaskUserResponseMessage (0 custom class methods, 3 custom properties)

#import "GTLRosetaskApiMessagesTaskUserResponseMessage.h"

// ----------------------------------------------------------------------------
//
//   GTLRosetaskApiMessagesTaskUserResponseMessage
//

@implementation GTLRosetaskApiMessagesTaskUserResponseMessage
@dynamic googlePlusId, lowercaseEmail, preferredName;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      @"google_plus_id", @"googlePlusId",
      @"lowercase_email", @"lowercaseEmail",
      @"preferred_name", @"preferredName",
      nil];
  return map;
}

@end
