/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLRosetaskConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   rosetask/v1
// Description:
//   Rose Task API

#import "GTLRosetaskConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeRosetaskUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";

// Order
NSString * const kGTLRosetaskOrderTitle = @"TITLE";
NSString * const kGTLRosetaskOrderWhen  = @"WHEN";
