/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLRosetaskTaskListProtoIdTitleTaskUserEmails.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   rosetask/v1
// Description:
//   Rose Task API
// Classes:
//   GTLRosetaskTaskListProtoIdTitleTaskUserEmails (0 custom class methods, 3 custom properties)

#import "GTLRosetaskTaskListProtoIdTitleTaskUserEmails.h"

// ----------------------------------------------------------------------------
//
//   GTLRosetaskTaskListProtoIdTitleTaskUserEmails
//

@implementation GTLRosetaskTaskListProtoIdTitleTaskUserEmails
@dynamic identifier, taskUserEmails, title;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      @"id", @"identifier",
      @"task_user_emails", @"taskUserEmails",
      nil];
  return map;
}

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[NSString class]
                                forKey:@"task_user_emails"];
  return map;
}

@end
