/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLRosetaskTask.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   rosetask/v1
// Description:
//   Rose Task API
// Classes:
//   GTLRosetaskTask (0 custom class methods, 6 custom properties)

#import "GTLRosetaskTask.h"

#import "GTLRosetaskUserMessage.h"

// ----------------------------------------------------------------------------
//
//   GTLRosetaskTask
//

@implementation GTLRosetaskTask
@dynamic assignedToEmail, complete, created, creator, taskListId, text;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      @"assigned_to_email", @"assignedToEmail",
      @"task_list_id", @"taskListId",
      nil];
  return map;
}

@end
