/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLRosetaskApiMessagesTaskListResponseMessage.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   rosetask/v1
// Description:
//   Rose Task API
// Classes:
//   GTLRosetaskApiMessagesTaskListResponseMessage (0 custom class methods, 4 custom properties)

#import "GTLRosetaskApiMessagesTaskListResponseMessage.h"

#import "GTLRosetaskApiMessagesTaskResponseMessage.h"
#import "GTLRosetaskApiMessagesTaskUserResponseMessage.h"

// ----------------------------------------------------------------------------
//
//   GTLRosetaskApiMessagesTaskListResponseMessage
//

@implementation GTLRosetaskApiMessagesTaskListResponseMessage
@dynamic identifier, taskUsers, tasks, title;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      @"id", @"identifier",
      @"task_users", @"taskUsers",
      nil];
  return map;
}

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      [GTLRosetaskApiMessagesTaskUserResponseMessage class], @"task_users",
      [GTLRosetaskApiMessagesTaskResponseMessage class], @"tasks",
      nil];
  return map;
}

@end
