/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLRosetaskTaskProtoIdTextTaskListIdDetailsCompleteAssignedToEmail.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   rosetask/v1
// Description:
//   Rose Task API
// Classes:
//   GTLRosetaskTaskProtoIdTextTaskListIdDetailsCompleteAssignedToEmail (0 custom class methods, 6 custom properties)

#import "GTLRosetaskTaskProtoIdTextTaskListIdDetailsCompleteAssignedToEmail.h"

// ----------------------------------------------------------------------------
//
//   GTLRosetaskTaskProtoIdTextTaskListIdDetailsCompleteAssignedToEmail
//

@implementation GTLRosetaskTaskProtoIdTextTaskListIdDetailsCompleteAssignedToEmail
@dynamic assignedToEmail, complete, details, identifier, taskListId, text;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      @"assigned_to_email", @"assignedToEmail",
      @"id", @"identifier",
      @"task_list_id", @"taskListId",
      nil];
  return map;
}

@end
