/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLRosetaskTaskList.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   rosetask/v1
// Description:
//   Rose Task API
// Classes:
//   GTLRosetaskTaskList (0 custom class methods, 5 custom properties)

#import "GTLRosetaskTaskList.h"

#import "GTLRosetaskUserMessage.h"

// ----------------------------------------------------------------------------
//
//   GTLRosetaskTaskList
//

@implementation GTLRosetaskTaskList
@dynamic created, creator, taskKeys, taskUserEmails, title;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      @"task_keys", @"taskKeys",
      @"task_user_emails", @"taskUserEmails",
      nil];
  return map;
}

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      [NSString class], @"task_keys",
      [NSString class], @"task_user_emails",
      nil];
  return map;
}

@end
