/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLRosetask.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   rosetask/v1
// Description:
//   Rose Task API

#import "GTLRosetaskConstants.h"

#import "GTLRosetaskApiMessagesTaskListListResponse.h"
#import "GTLRosetaskApiMessagesTaskListResponseMessage.h"
#import "GTLRosetaskApiMessagesTaskResponseMessage.h"
#import "GTLRosetaskApiMessagesTaskUserResponseMessage.h"
#import "GTLRosetaskTask.h"
#import "GTLRosetaskTaskCollection.h"
#import "GTLRosetaskTaskList.h"
#import "GTLRosetaskTaskUser.h"

#import "GTLQueryRosetask.h"
#import "GTLServiceRosetask.h"
