/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLRosetaskTask.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   rosetask/v1
// Description:
//   Rose Task API
// Classes:
//   GTLRosetaskTask (0 custom class methods, 6 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLRosetaskUserMessage;

// ----------------------------------------------------------------------------
//
//   GTLRosetaskTask
//

@interface GTLRosetaskTask : GTLObject
@property (copy) NSString *assignedToEmail;
@property (retain) NSNumber *complete;  // boolValue
@property (copy) NSString *created;

// ProtoRPC container for users.User objects. Attributes: email: String; The
// email of the user. auth_domain: String; The auth domain of the user. user_id:
// String; The user ID. federated_identity: String; The federated identity of
// the user.
@property (retain) GTLRosetaskUserMessage *creator;

@property (retain) NSNumber *taskListId;  // longLongValue
@property (copy) NSString *text;
@end
