/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLRosetaskUserMessage.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   rosetask/v1
// Description:
//   Rose Task API
// Classes:
//   GTLRosetaskUserMessage (0 custom class methods, 4 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLRosetaskUserMessage
//

// ProtoRPC container for users.User objects. Attributes: email: String; The
// email of the user. auth_domain: String; The auth domain of the user. user_id:
// String; The user ID. federated_identity: String; The federated identity of
// the user.

@interface GTLRosetaskUserMessage : GTLObject
@property (copy) NSString *authDomain;
@property (copy) NSString *email;
@property (copy) NSString *federatedIdentity;
@property (copy) NSString *userId;
@end
