/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLServiceRosetask.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   rosetask/v1
// Description:
//   Rose Task API
// Classes:
//   GTLServiceRosetask (0 custom class methods, 0 custom properties)

#import "GTLRosetask.h"

@implementation GTLServiceRosetask

#if DEBUG
// Method compiled in debug builds just to check that all the needed support
// classes are present at link time.
+ (NSArray *)checkClasses {
  NSArray *classes = [NSArray arrayWithObjects:
                      [GTLQueryRosetask class],
                      [GTLRosetaskApiMessagesTaskListListResponse class],
                      [GTLRosetaskApiMessagesTaskListResponseMessage class],
                      [GTLRosetaskApiMessagesTaskResponseMessage class],
                      [GTLRosetaskApiMessagesTaskUserResponseMessage class],
                      [GTLRosetaskTask class],
                      [GTLRosetaskTaskCollection class],
                      [GTLRosetaskTaskList class],
                      [GTLRosetaskTaskListProtoIdTitleTaskUserEmails class],
                      [GTLRosetaskTaskProtoIdTextTaskListIdDetailsCompleteAssignedToEmail class],
                      [GTLRosetaskTaskUser class],
                      [GTLRosetaskTaskUserProtoLowercaseEmailPreferredNameGooglePlusId class],
                      nil];
  return classes;
}
#endif  // DEBUG

- (id)init {
  self = [super init];
  if (self) {
    // Version from discovery.
    self.apiVersion = @"v1";

    // From discovery.  Where to send JSON-RPC.
    // Turn off prettyPrint for this service to save bandwidth (especially on
    // mobile). The fetcher logging will pretty print.
    self.rpcURL = [NSURL URLWithString:@"https://None/_ah/api/rpc?prettyPrint=false"];
  }
  return self;
}

@end
